### ISSUE TITLE
Retrieve printer port name instead of the printer identifier

### ISSUE THREAD

**Issue by asa47** [star-micronics/StarXpand-SDK-iOS#10]
## Description

Is it possible to retrieve the printer "port name" instead of the "BT address/identifier"?

We have looked at the object returned by the `manager.startDiscovery <StarPrinter>` and `printer.getStatus() <StarPrinterStatus>` but we could't find the printer "port name".

For example, we have a mC_Print2 printer and the port name is set to "BT:mC-Print2". We were hoping it would have been included in `StarPrinter` or `StarPrinterStatus` instances. 

However, we are getting the following response with `manager.startDiscovery`: 
 
```
information : Optional(model : mC_Print2, emulation : starPRNT, connectionIdentifier : specifiedIdentifier : nil, macAddress : Optional("0011621BE452"), bluetoothAddress : Optional("0011621972B0"), usbSerialNumber : Optional("2600318070600032"), nicInformation : nil, eaAccessoryInformation : Optional(accessory : Optional(<EAAccessory: 0x2821ac370> { 
  connected:YES 
  connectionID:45536251 
  name: mC-Print2 
  manufacturer: Star Micronics 
  modelNumber: MCP21LB 
  serialNumber: 2600318070600032 
  ppid: (null) 
  regioncode: (null) 
  firmwareRevisionActive: 1.0.0 
  firmwareRevisionPending: (null) 
  hardwareRevision: 1.0.0 
  dockType:  
  certSerial: 15 bytes 
  certData: 908 bytes 
  protocols: (
    "jp.star-m.starpro"
) 
  delegate: (null) 
})), bluetoothLEInformation : nil), connectionSettings : interfaceType : 2, identifier : 2600318070600032, autoSwitchInterface : false, processQueue : <OS_dispatch_queue_serial: StarIO10.StarPrinter>, _printerDelegate : nil, _drawerDelegate : nil, _inputDeviceDelegate : nil, _displayDelegate : nil, monitor : nil, openTimeout : 10000, getStatusTimeout : 5000, printTimeout : 30000, port : nil, lock : <NSLock: 0x280799d40>{name = nil}, isOpened : false, printControl : nil

```

And the following response with `printer.getStatus()`:

```
hasError : false, coverOpen : false, drawerOpenCloseSignal : false, paperEmpty : false, paperNearEmpty : false, detail : version : Optional(5), printHeadOverTemperature : Optional(false), unrecoverableError : Optional(false), cutterError : Optional(false), printHeadThermistorError : Optional(false), receiveBufferOverflow : Optional(false), paperSeparatorError : Optional(false), paperJamError : Optional(false), paperPresent : Optional(false), etbCounter : Optional(0), boardOverTemperature : Optional(false), drawerOpenError : Optional(false), flashAccessError : Optional(false), eepromAccessError : Optional(false), sramAccessError : Optional(false), boardThermistorError : Optional(false), sensorAdjustmentError : Optional(false), printUnitOpen : Optional(false), connectedInterface : Optional(2)
```

## Your device where the bug occurs 
 - Device: 
    *iPad (5th generation)*
 - OS:
    *iOS 15.0*

## Your printer
- Model Names:
    *mC-Print2*
- Firmware Version:
    *1.0.0*
- Interface:
    *BT*

## Your development environment
The result of executing the command `ver` on Windows, `sw_vers` on macOS, `uname –a` on Linux, or these equivalent commands.

ProductName: macOS
ProductVersion: 12.1
BuildVersion: 21C52

## Additional context
Any other context about your topic.
